divdamp_order: COMBINED
divdamp_trans_end: 17500.0
divdamp_trans_start: 12500.0
divdamp_type: THREE_DIMENSIONAL
fourth_order_divdamp_factor: 0.0025
fourth_order_divdamp_factor2: 0.004
fourth_order_divdamp_factor3: 0.004
fourth_order_divdamp_factor4: 0.004
fourth_order_divdamp_z: 32500.0
fourth_order_divdamp_z2: 40000.0
fourth_order_divdamp_z3: 60000.0
fourth_order_divdamp_z4: 80000.0
iadv_rhotheta: MIURA
iau_wgt_dyn: 0.0
igradp_method: TAYLOR_HYDRO
is_iau_active: false
itime_scheme: MOST_EFFICIENT
max_nudging_coefficient: 0.1
ndyn_substeps: 5
rayleigh_coeff: 0.1
rayleigh_type: KLEMP
rhotheta_offctr: -0.1
veladv_offctr: 0.25
